workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    sample-source:
        inputs:
            - location: openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/placeholderapi/placeholderapi/sample-source
targets:
    my-first-target:
        target: typescript
        source: sample-source
        publish:
            npm:
                token: $npm_token
