/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type EventCreate = {
    /**
     * The name of the event.
     */
    name: string;
    /**
     * The channel name where the event is registered.
     */
    channel: string;
    /**
     * An optional icon representing the event.
     */
    icon?: string | undefined;
    /**
     * Whether to notify users about the event.
     */
    notify: boolean;
    /**
     * Additional tags providing context for the event.
     */
    tags?: { [k: string]: string } | undefined;
};

/** @internal */
export namespace EventCreate$ {
    export const inboundSchema: z.ZodType<EventCreate, z.ZodTypeDef, unknown> = z
        .object({
            name: z.string(),
            channel: z.string(),
            icon: z.string().optional(),
            notify: z.boolean(),
            tags: z.record(z.string()).optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                channel: v.channel,
                ...(v.icon === undefined ? null : { icon: v.icon }),
                notify: v.notify,
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });

    export type Outbound = {
        name: string;
        channel: string;
        icon?: string | undefined;
        notify: boolean;
        tags?: { [k: string]: string } | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, EventCreate> = z
        .object({
            name: z.string(),
            channel: z.string(),
            icon: z.string().optional(),
            notify: z.boolean(),
            tags: z.record(z.string()).optional(),
        })
        .transform((v) => {
            return {
                name: v.name,
                channel: v.channel,
                ...(v.icon === undefined ? null : { icon: v.icon }),
                notify: v.notify,
                ...(v.tags === undefined ? null : { tags: v.tags }),
            };
        });
}
